package panels;

import javax.swing.JRadioButton;

import auxiliares.TransformacoesImagemEnum;

/**
 * Representa o menu para manipulacao da circunferencia
 *
 */
public class PanelMenuMorfologia extends javax.swing.JPanel {

    private static PanelMenuMorfologia instance;
    private TransformacoesImagemEnum tipoAlgoritimo;
    private float dados;

    public static synchronized PanelMenuMorfologia getInstance() {
        if (instance == null) {
            instance = new PanelMenuMorfologia();
        }
        return instance;
    }
    
    /**
     * Construtor
     */
    private PanelMenuMorfologia() {
        initComponents();
        panelConfigGamma.setVisible(false);
    }

    public float getDados() {
        return (float) tfGammaY.getValue();
    }

    public TransformacoesImagemEnum getTipoAlgoritimo() {
        if (rbDilatacao.isSelected()) {
            setTipoAlgoritimo(TransformacoesImagemEnum.NEGATIVO);
        } else if (rbAbertura.isSelected()) {
            setTipoAlgoritimo(TransformacoesImagemEnum.GAMMA);
        } else if (rbFechamento.isSelected()) {
            setTipoAlgoritimo(TransformacoesImagemEnum.LOG);
        } else if (rbReducao.isSelected()) {
        	
        } else if (rbAfinamento.isSelected()) {
        	
        }
        return tipoAlgoritimo;
    }

    public void setTipoAlgoritimo(TransformacoesImagemEnum tipoAlgoritimo) {
        this.tipoAlgoritimo = tipoAlgoritimo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	// Dilatacao, Abertura, Fechamento, Reducao, Afinamento

        buttonGroupFiltros = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        
        rbDilatacao = new javax.swing.JRadioButton();
        rbAbertura = new javax.swing.JRadioButton();
        rbFechamento = new javax.swing.JRadioButton();
        rbReducao = new javax.swing.JRadioButton();
        rbAfinamento = new javax.swing.JRadioButton();
        
        panelConfigGamma = new javax.swing.JPanel();
        lbInfor = new javax.swing.JLabel();
        tfGammaY = new javax.swing.JSpinner();

        setMaximumSize(new java.awt.Dimension(240, 32767));
        setMinimumSize(new java.awt.Dimension(240, 0));
        setPreferredSize(new java.awt.Dimension(240, 779));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        buttonGroupFiltros.add(rbDilatacao);
        rbDilatacao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbDilatacao.setSelected(true);
        rbDilatacao.setText("Dilatacao");
        rbDilatacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSelect(evt);
            }
        });

        buttonGroupFiltros.add(rbAbertura);
        rbAbertura.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbAbertura.setText("Abertura");
        rbAbertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSelect(evt);
            }
        });

        buttonGroupFiltros.add(rbFechamento);
        rbFechamento.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbFechamento.setText("Fechamento");
        rbFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSelect(evt);
            }
        });
        
        buttonGroupFiltros.add(rbReducao);
        rbReducao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbReducao.setText("Fechamento");
        rbReducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSelect(evt);
            }
        });
        
        buttonGroupFiltros.add(rbAfinamento);
        rbAfinamento.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbAfinamento.setText("Fechamento");
        rbAfinamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSelect(evt);
            }
        });

        panelConfigGamma.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados para operacao"));

        lbInfor.setText("c = 1 e y = (0 <= y <= 1)");

        tfGammaY.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
        tfGammaY.setMinimumSize(new java.awt.Dimension(29, 30));

        javax.swing.GroupLayout panelConfigGammaLayout = new javax.swing.GroupLayout(panelConfigGamma);
        panelConfigGamma.setLayout(panelConfigGammaLayout);
        panelConfigGammaLayout.setHorizontalGroup(
            panelConfigGammaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigGammaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConfigGammaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfigGammaLayout.createSequentialGroup()
                        .addComponent(lbInfor)
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addComponent(tfGammaY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelConfigGammaLayout.setVerticalGroup(
            panelConfigGammaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigGammaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInfor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfGammaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelConfigGamma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbDilatacao)
                            .addComponent(rbAbertura)
                            .addComponent(rbAfinamento)
                            .addComponent(rbReducao)
                            .addComponent(rbFechamento))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbDilatacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbAfinamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbAbertura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbReducao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFechamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(panelConfigGamma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(481, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbSelect(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSelect
        JRadioButton radio = (JRadioButton) evt.getSource();
        PanelTranformacoes.getInstance().setTitle("Morfologia " + radio.getText());
        PanelTranformacoes.panelImgOutput.removeAll();
        PanelTranformacoes.panelImgOutput.repaint();
        
        if (rbDilatacao.isSelected()) {
            panelConfigGamma.setVisible(false);
        } else {
            panelConfigGamma.setVisible(true);
            if (rbFechamento.isSelected()) {
                lbInfor.setText("c = 1 e y = (0 <= y <= 1)");
            } else {
                lbInfor.setText("Constante \"a\" e S=alog(r+1)");
            }
        }
    }//GEN-LAST:event_rbSelect


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFiltros;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbInfor;
    private javax.swing.JPanel panelConfigGamma;
    private javax.swing.JRadioButton rbDilatacao;
    private javax.swing.JRadioButton rbFechamento;
    private javax.swing.JRadioButton rbAbertura;
    private javax.swing.JRadioButton rbAfinamento;
    private javax.swing.JRadioButton rbReducao;
    private javax.swing.JSpinner tfGammaY;
    // End of variables declaration//GEN-END:variables
}
